### ISSUE TITLE
Innspill til oppsett-avsnitt

### ISSUE THREAD

**Issue by guroseter** [ewendel/elm-workshop#8]
Et par ting jeg tenkte på mens jeg gjorde workshoppen

- Avsnittet om oppsett er forvirrende, de to linkene "elm-plugin" og "Atom editor setup" leder vel til samme side? Kanskje dere kan klare dere med bare den plugin-lenken og å si at dere anbefaler å bruke atom. Når man klikker på plugin-lenken står jo atom der som første punkt.
- Må man ikke kjøre `elm-package install` også? Det klaget i hvert fall min editor på.

**Comment by ingara** [comment]
Takk for innspill.

"plugin"-lenken går til den offisielle nettsiden med lenker videre til plugins for forskjellige editorer.
"Atom editor setup"-lenken går direkte til oppsettet som trengs for Atom.

Man skal ikke trenge å kjøre `elm-package install` manuelt, da det skal bli tatt hånd om av `npm start`-scriptet.

**Comment by guroseter** [comment]
Ah, never mind, jeg hadde bare kjørt `npm install`. 

Ja, jeg skjønner forskjellen på de to lenkene. Men jeg tror det er *bedre* å bare oppgi den ene lenken, da man kan få inntrykk av at man må inn på begge sidene.

**Comment by ingara** [comment]
Skjønner. Jeg syns vi bør ha begge lenkene, da det alltid er noen som er veldig glad i {sett inn editor her}, men vi kan nok gjøre intensjonen om at vi anbefaler Atom tydeligere. Har du lyst til å sende en PR på det?

**Comment by guroseter** [comment]
Ja, jeg mener dropp atom-lenken og bare ha den generelle. Det er jo bare et klikk til s

**Comment by guroseter** [comment]
så er du på Atom-siden. Jeg lager en PR.

**Comment by ingara** [comment]
Supert!
